dify:
  api-endpoint: http://localhost/v1
  dataset-api-key: toBeSet

---
spring:
  config:
    activate:
      on-profile: test

mock-server:
  endpoint: http://mock-server.tool.net:1080

dify:
  api-endpoint: http://mock-server.tool.net:1080/dify/v1
  dataset-api-key: difyDatasetApiKey
